//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 12:40:11 PM MEZ 
//


package org.sciplore.rest;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for documentType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="documentType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}titleType"/>
 *         &lt;element name="abstract" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}abstractType" minOccurs="0"/>
 *         &lt;element name="authors" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}authorsType" minOccurs="0"/>
 *         &lt;element name="keywords" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}keywordsType" minOccurs="0"/>
 *         &lt;element name="fulltexts" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}fulltextsType" minOccurs="0"/>
 *         &lt;element name="references" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}referencesType" minOccurs="0"/>
 *         &lt;element name="cited_by" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}cited_byType" minOccurs="0"/>
 *         &lt;element name="related_documents" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}related_documentsType" minOccurs="0"/>
 *         &lt;element name="doi" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}doiType" minOccurs="0"/>
 *         &lt;element name="venue" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}venueType" minOccurs="0"/>
 *         &lt;element name="issn" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}issnType" minOccurs="0"/>
 *         &lt;element name="isbn" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}isbnType" minOccurs="0"/>
 *         &lt;element name="language" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}languageType" minOccurs="0"/>
 *         &lt;element name="series" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}seriesType" minOccurs="0"/>
 *         &lt;element name="pages" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}pagesType" minOccurs="0"/>
 *         &lt;element name="volume" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}volumeType" minOccurs="0"/>
 *         &lt;element name="edition" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}editionType" minOccurs="0"/>
 *         &lt;element name="number" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}numberType" minOccurs="0"/>
 *         &lt;element name="publishdate" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}publishdateType" minOccurs="0"/>
 *         &lt;element name="annotations" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}annotationsType" minOccurs="0"/>
 *         &lt;element name="relatedness" type="{http://dke113.cs.uni-magdeburg.de/rest/xml}relatednessType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="type" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="hash" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="id" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedLong" />
 *       &lt;attribute name="href" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "documentType", propOrder = {
    "title",
    "_abstract",
    "authors",
    "keywords",
    "fulltexts",
    "references",
    "citedBy",
    "relatedDocuments",
    "doi",
    "venue",
    "issn",
    "isbn",
    "language",
    "series",
    "pages",
    "volume",
    "edition",
    "number",
    "publishdate",
    "annotations",
    "relatedness"
})
public class DocumentType {

    @XmlElement(required = true)
    protected TitleType title;
    @XmlElement(name = "abstract")
    protected AbstractType _abstract;
    protected AuthorsType authors;
    protected KeywordsType keywords;
    protected FulltextsType fulltexts;
    protected ReferencesType references;
    @XmlElement(name = "cited_by")
    protected CitedByType citedBy;
    @XmlElement(name = "related_documents")
    protected RelatedDocumentsType relatedDocuments;
    protected DoiType doi;
    protected VenueType venue;
    protected IssnType issn;
    protected IsbnType isbn;
    protected LanguageType language;
    protected SeriesType series;
    protected PagesType pages;
    protected VolumeType volume;
    protected EditionType edition;
    protected NumberType number;
    protected PublishdateType publishdate;
    protected AnnotationsType annotations;
    protected RelatednessType relatedness;
    @XmlAttribute(required = true)
    protected String type;
    @XmlAttribute(required = true)
    protected String hash;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "unsignedLong")
    protected BigInteger id;
    @XmlAttribute(required = true)
    protected String href;

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link TitleType }
     *     
     */
    public TitleType getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link TitleType }
     *     
     */
    public void setTitle(TitleType value) {
        this.title = value;
    }

    /**
     * Gets the value of the abstract property.
     * 
     * @return
     *     possible object is
     *     {@link AbstractType }
     *     
     */
    public AbstractType getAbstract() {
        return _abstract;
    }

    /**
     * Sets the value of the abstract property.
     * 
     * @param value
     *     allowed object is
     *     {@link AbstractType }
     *     
     */
    public void setAbstract(AbstractType value) {
        this._abstract = value;
    }

    /**
     * Gets the value of the authors property.
     * 
     * @return
     *     possible object is
     *     {@link AuthorsType }
     *     
     */
    public AuthorsType getAuthors() {
        return authors;
    }

    /**
     * Sets the value of the authors property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuthorsType }
     *     
     */
    public void setAuthors(AuthorsType value) {
        this.authors = value;
    }

    /**
     * Gets the value of the keywords property.
     * 
     * @return
     *     possible object is
     *     {@link KeywordsType }
     *     
     */
    public KeywordsType getKeywords() {
        return keywords;
    }

    /**
     * Sets the value of the keywords property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeywordsType }
     *     
     */
    public void setKeywords(KeywordsType value) {
        this.keywords = value;
    }

    /**
     * Gets the value of the fulltexts property.
     * 
     * @return
     *     possible object is
     *     {@link FulltextsType }
     *     
     */
    public FulltextsType getFulltexts() {
        return fulltexts;
    }

    /**
     * Sets the value of the fulltexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link FulltextsType }
     *     
     */
    public void setFulltexts(FulltextsType value) {
        this.fulltexts = value;
    }

    /**
     * Gets the value of the references property.
     * 
     * @return
     *     possible object is
     *     {@link ReferencesType }
     *     
     */
    public ReferencesType getReferences() {
        return references;
    }

    /**
     * Sets the value of the references property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferencesType }
     *     
     */
    public void setReferences(ReferencesType value) {
        this.references = value;
    }

    /**
     * Gets the value of the citedBy property.
     * 
     * @return
     *     possible object is
     *     {@link CitedByType }
     *     
     */
    public CitedByType getCitedBy() {
        return citedBy;
    }

    /**
     * Sets the value of the citedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link CitedByType }
     *     
     */
    public void setCitedBy(CitedByType value) {
        this.citedBy = value;
    }

    /**
     * Gets the value of the relatedDocuments property.
     * 
     * @return
     *     possible object is
     *     {@link RelatedDocumentsType }
     *     
     */
    public RelatedDocumentsType getRelatedDocuments() {
        return relatedDocuments;
    }

    /**
     * Sets the value of the relatedDocuments property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatedDocumentsType }
     *     
     */
    public void setRelatedDocuments(RelatedDocumentsType value) {
        this.relatedDocuments = value;
    }

    /**
     * Gets the value of the doi property.
     * 
     * @return
     *     possible object is
     *     {@link DoiType }
     *     
     */
    public DoiType getDoi() {
        return doi;
    }

    /**
     * Sets the value of the doi property.
     * 
     * @param value
     *     allowed object is
     *     {@link DoiType }
     *     
     */
    public void setDoi(DoiType value) {
        this.doi = value;
    }

    /**
     * Gets the value of the venue property.
     * 
     * @return
     *     possible object is
     *     {@link VenueType }
     *     
     */
    public VenueType getVenue() {
        return venue;
    }

    /**
     * Sets the value of the venue property.
     * 
     * @param value
     *     allowed object is
     *     {@link VenueType }
     *     
     */
    public void setVenue(VenueType value) {
        this.venue = value;
    }

    /**
     * Gets the value of the issn property.
     * 
     * @return
     *     possible object is
     *     {@link IssnType }
     *     
     */
    public IssnType getIssn() {
        return issn;
    }

    /**
     * Sets the value of the issn property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssnType }
     *     
     */
    public void setIssn(IssnType value) {
        this.issn = value;
    }

    /**
     * Gets the value of the isbn property.
     * 
     * @return
     *     possible object is
     *     {@link IsbnType }
     *     
     */
    public IsbnType getIsbn() {
        return isbn;
    }

    /**
     * Sets the value of the isbn property.
     * 
     * @param value
     *     allowed object is
     *     {@link IsbnType }
     *     
     */
    public void setIsbn(IsbnType value) {
        this.isbn = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link LanguageType }
     *     
     */
    public LanguageType getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link LanguageType }
     *     
     */
    public void setLanguage(LanguageType value) {
        this.language = value;
    }

    /**
     * Gets the value of the series property.
     * 
     * @return
     *     possible object is
     *     {@link SeriesType }
     *     
     */
    public SeriesType getSeries() {
        return series;
    }

    /**
     * Sets the value of the series property.
     * 
     * @param value
     *     allowed object is
     *     {@link SeriesType }
     *     
     */
    public void setSeries(SeriesType value) {
        this.series = value;
    }

    /**
     * Gets the value of the pages property.
     * 
     * @return
     *     possible object is
     *     {@link PagesType }
     *     
     */
    public PagesType getPages() {
        return pages;
    }

    /**
     * Sets the value of the pages property.
     * 
     * @param value
     *     allowed object is
     *     {@link PagesType }
     *     
     */
    public void setPages(PagesType value) {
        this.pages = value;
    }

    /**
     * Gets the value of the volume property.
     * 
     * @return
     *     possible object is
     *     {@link VolumeType }
     *     
     */
    public VolumeType getVolume() {
        return volume;
    }

    /**
     * Sets the value of the volume property.
     * 
     * @param value
     *     allowed object is
     *     {@link VolumeType }
     *     
     */
    public void setVolume(VolumeType value) {
        this.volume = value;
    }

    /**
     * Gets the value of the edition property.
     * 
     * @return
     *     possible object is
     *     {@link EditionType }
     *     
     */
    public EditionType getEdition() {
        return edition;
    }

    /**
     * Sets the value of the edition property.
     * 
     * @param value
     *     allowed object is
     *     {@link EditionType }
     *     
     */
    public void setEdition(EditionType value) {
        this.edition = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link NumberType }
     *     
     */
    public NumberType getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link NumberType }
     *     
     */
    public void setNumber(NumberType value) {
        this.number = value;
    }

    /**
     * Gets the value of the publishdate property.
     * 
     * @return
     *     possible object is
     *     {@link PublishdateType }
     *     
     */
    public PublishdateType getPublishdate() {
        return publishdate;
    }

    /**
     * Sets the value of the publishdate property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublishdateType }
     *     
     */
    public void setPublishdate(PublishdateType value) {
        this.publishdate = value;
    }

    /**
     * Gets the value of the annotations property.
     * 
     * @return
     *     possible object is
     *     {@link AnnotationsType }
     *     
     */
    public AnnotationsType getAnnotations() {
        return annotations;
    }

    /**
     * Sets the value of the annotations property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnnotationsType }
     *     
     */
    public void setAnnotations(AnnotationsType value) {
        this.annotations = value;
    }

    /**
     * Gets the value of the relatedness property.
     * 
     * @return
     *     possible object is
     *     {@link RelatednessType }
     *     
     */
    public RelatednessType getRelatedness() {
        return relatedness;
    }

    /**
     * Sets the value of the relatedness property.
     * 
     * @param value
     *     allowed object is
     *     {@link RelatednessType }
     *     
     */
    public void setRelatedness(RelatednessType value) {
        this.relatedness = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the hash property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHash() {
        return hash;
    }

    /**
     * Sets the value of the hash property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHash(String value) {
        this.hash = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setId(BigInteger value) {
        this.id = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

}
