//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 12:40:11 PM MEZ 
//


package org.sciplore.rest;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sciplore.rest package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Webservice_QNAME = new QName("http://dke113.cs.uni-magdeburg.de/rest/xml", "webservice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sciplore.rest
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NumberType }
     * 
     */
    public NumberType createNumberType() {
        return new NumberType();
    }

    /**
     * Create an instance of {@link EditionType }
     * 
     */
    public EditionType createEditionType() {
        return new EditionType();
    }

    /**
     * Create an instance of {@link AnnotationType }
     * 
     */
    public AnnotationType createAnnotationType() {
        return new AnnotationType();
    }

    /**
     * Create an instance of {@link VenueType }
     * 
     */
    public VenueType createVenueType() {
        return new VenueType();
    }

    /**
     * Create an instance of {@link KeywordType }
     * 
     */
    public KeywordType createKeywordType() {
        return new KeywordType();
    }

    /**
     * Create an instance of {@link RelatednessType }
     * 
     */
    public RelatednessType createRelatednessType() {
        return new RelatednessType();
    }

    /**
     * Create an instance of {@link UserType }
     * 
     */
    public UserType createUserType() {
        return new UserType();
    }

    /**
     * Create an instance of {@link KeywordsType }
     * 
     */
    public KeywordsType createKeywordsType() {
        return new KeywordsType();
    }

    /**
     * Create an instance of {@link CitedByType }
     * 
     */
    public CitedByType createCitedByType() {
        return new CitedByType();
    }

    /**
     * Create an instance of {@link PublishdateType }
     * 
     */
    public PublishdateType createPublishdateType() {
        return new PublishdateType();
    }

    /**
     * Create an instance of {@link FulltextType }
     * 
     */
    public FulltextType createFulltextType() {
        return new FulltextType();
    }

    /**
     * Create an instance of {@link FulltextsType }
     * 
     */
    public FulltextsType createFulltextsType() {
        return new FulltextsType();
    }

    /**
     * Create an instance of {@link AuthorType }
     * 
     */
    public AuthorType createAuthorType() {
        return new AuthorType();
    }

    /**
     * Create an instance of {@link AbstractType }
     * 
     */
    public AbstractType createAbstractType() {
        return new AbstractType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link LanguageType }
     * 
     */
    public LanguageType createLanguageType() {
        return new LanguageType();
    }

    /**
     * Create an instance of {@link SeriesType }
     * 
     */
    public SeriesType createSeriesType() {
        return new SeriesType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link PagesType }
     * 
     */
    public PagesType createPagesType() {
        return new PagesType();
    }

    /**
     * Create an instance of {@link AnnotationsType }
     * 
     */
    public AnnotationsType createAnnotationsType() {
        return new AnnotationsType();
    }

    /**
     * Create an instance of {@link WebserviceType }
     * 
     */
    public WebserviceType createWebserviceType() {
        return new WebserviceType();
    }

    /**
     * Create an instance of {@link IssnType }
     * 
     */
    public IssnType createIssnType() {
        return new IssnType();
    }

    /**
     * Create an instance of {@link ReferenceType }
     * 
     */
    public ReferenceType createReferenceType() {
        return new ReferenceType();
    }

    /**
     * Create an instance of {@link DoiType }
     * 
     */
    public DoiType createDoiType() {
        return new DoiType();
    }

    /**
     * Create an instance of {@link AuthorsType }
     * 
     */
    public AuthorsType createAuthorsType() {
        return new AuthorsType();
    }

    /**
     * Create an instance of {@link ReferencesType }
     * 
     */
    public ReferencesType createReferencesType() {
        return new ReferencesType();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link RelatedDocumentsType }
     * 
     */
    public RelatedDocumentsType createRelatedDocumentsType() {
        return new RelatedDocumentsType();
    }

    /**
     * Create an instance of {@link IsbnType }
     * 
     */
    public IsbnType createIsbnType() {
        return new IsbnType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link WebserviceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://dke113.cs.uni-magdeburg.de/rest/xml", name = "webservice")
    public JAXBElement<WebserviceType> createWebservice(WebserviceType value) {
        return new JAXBElement<WebserviceType>(_Webservice_QNAME, WebserviceType.class, null, value);
    }

}
