//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.03.23 at 12:40:11 PM MEZ 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dke113.cs.uni-magdeburg.de/rest/xml", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.sciplore.rest;
